<?php

/**
 * @file
 * A block module that show a share button.
 */

/**
 * Implements hook_block_info().
 */
function share_button_block_info() {
  $blocks = array();
  $blocks['share_button_block1'] = array(
  	// The name that will appear in the block list.
    'info' => t('Share button block'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  
  return $blocks;
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function share_button_help($path, $arg) {
  switch ($path) {
    case "admin/help#share_button":
      return '' . t("Displays a button in a block to share my page") . '';
      break;
  }
} 

/**
 * Implements hook_block_view().
 */
function share_button_block_view($delta = '') {
  $block = array();
	switch ($delta) {
		case 'share_button_block1':
  		$block['subject'] = t('Share button');
      $block['content'] = _share_button_block_contents($delta);
    break;
	}
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function share_button_block_configure($delta='') {
  $form = array();

  switch($delta) {
    case 'share_button_block1' :
      // Checkbox form element

      $form['share_button_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Share button settings'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#weight' => -1,
      );

      $form['share_button_settings']['opt_facebook'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Facebook option'),
        '#default_value' => variable_get('opt_facebook_value', 1),
      );

      $form['share_button_settings']['opt_twitter'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Twitter option'),
        '#default_value' => variable_get('opt_twitter_value', 1),
      );

      $form['share_button_settings']['opt_googleplus'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Google Plus option'),
        '#default_value' => variable_get('opt_googleplus_value', 1),
      );

      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */

function share_button_block_save ($delta = '', $edit = array()){

  switch ($delta) {
    case 'share_button_block1':
      // Saving the on/off varibles...
      variable_set('opt_facebook_value', $edit['opt_facebook']);
      variable_set('opt_twitter_value', $edit['opt_twitter']);
      variable_set('opt_googleplus_value', $edit['opt_googleplus']);
      break;

  }
}


/**
 * Implements hook_theme().
 */
function share_button_theme() {
  $module_path = drupal_get_path('module', 'share_button');
  $base = array(
    'path' => "$module_path/theme",   
  );
  return array(
    'share_button_block_contents' => $base + array(
      'variables' => array('items' => NULL,),
      'template' => 'share_button-block1--block',
    ),
  );
}


/**
 * Callback implemented by hook_block_view().
 */
function _share_button_block_contents($block_id) {
  $items = array();

  $page_url = urlencode($GLOBALS['base_root'].request_uri());
  $page_title = urlencode(drupal_get_title());

  switch ($block_id) {
    case 'share_button_block1':
      $items = array(
        'share_page' => $page_url,
        'share_title' => $page_title,
        'opt_facebook' => variable_get('opt_facebook_value', 1),
        'opt_twitter' => variable_get('opt_twitter_value', 1),
        'opt_googleplus' => variable_get('opt_googleplus_value', 1),
      );
      break;
  }
  return theme('share_button_block_contents', array('items' => $items));

}